worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    client_max_body_size 0;

    server {
        listen 127.0.0.1:59002;
        server_name _;

        # =========================
        # MinIO 文件
        # =========================

        location /files/ {

            rewrite ^/files/(.*) /$1 break;

            proxy_pass http://127.0.0.1:9000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_buffering off;
            proxy_request_buffering off;

            chunked_transfer_encoding off;

            proxy_intercept_errors on;

            proxy_connect_timeout 300;
            proxy_read_timeout 300;
            proxy_send_timeout 300;

            proxy_redirect off;

            expires 7d;

            add_header XCDN-Cache "$upstream_cache_status";
        }

        # =========================
        # MinIO Web UI
        # =========================

        location /minio/ui/ {

            rewrite ^/minio/ui/(.*) /$1 break;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;

            real_ip_header X-Real-IP;

            proxy_connect_timeout 300;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_read_timeout 300;
            proxy_send_timeout 300;

            chunked_transfer_encoding off;

            proxy_pass http://127.0.0.1:9001/minio/ui/;
        }
    }
}