server:
  port: 10201

spring:
  application:
    name: blog-pi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.3:3306/blog_pi?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: MySql@Admin123*.

  data:
    redis:
      database: 0
      host: 172.18.0.6
      port: 6379
      password: redis-960@*

netty:
  ip: 49.232.129.253
  port: 60032

  registerCode: 1:2ecfb95116de4967afe7710e11ac00b4

mqtt:
  ip: 172.18.0.4
  port: 1883
  username: admin
  password: public
  clientId: SMP1

ftp:
  ip: 49.232.129.253
  port: 61121
  username: system
  password: Ftp@Admin123*.