server:
  port: 60002
  servlet:
    context-path: /auth

jasypt:
  encryptor:
    password: gszero

#logging:
#  level:
#    org:
#      springframework:
#        security: trace

spring:
  application:
    name: blog-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.3:3306/blog_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: ENC(CHAMoyE8XiIijQ7z2dhetMNMdeNXZhohLXw8mQ6KniCHgGtzfGHCyg==)
  data:
    redis:
      database: 0
      host: 172.18.0.6
      port: 6379
      password: ENC(o8ZdpLA+3lVokD4Xd5801OYjaJCXdtKIUqPbz8+fU8s=)

rocketmq:
  name-server: 172.18.0.8:9876 # 访问地址
  producer:
    group: blog-auth # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
  consumer:
    groupName: blog-auth
    namesrvAddr: 172.18.0.8:9876 # mq的nameserver地址
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: BLOG_USER_DATA~*;BLOG_SYSTEM_DATA~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1

easy-es:
  enable: true
  address : 172.18.0.10:9200
  schema: http
  username: elastic
  password: ENC(j3dQw+Kb0iGoyP2facAeOOCbqisES4HLP9NMuKIj/s9fXTtoOzHHXw==)

# 服务器内存限制，停用xxlJob
#xxl:
#  job:
#    admin:
#      addresses: http://172.18.0.12:8080/xxl-job-admin
#    accessToken: aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789+=
#    executor:
#      appname: ${spring.application.name}
#      address:
#      ip:
#      port: 60022
#      logpath: /opt/docker/xxlJob/logs
#      logretentiondays: 10

redirect:
  login: http://49.232.129.253/login
  callback: http://49.232.129.253/callback
  serviceIp: http://49.232.129.253/api

auth:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveUhfCOcSe1tvyOrkDlQfTA4kykqbcwkAxUyQk+DiDd1k725zfYNKsFWgy5acW+NLXIHv4LCTKI76vFNRplTcXtHSkvLkGCKVd+gbEhH0+o46Zpa9piy2/AOlUxPzExjvijfjw/JbFTrLVHjyBJ/H6ed1CAtKbcNIjtpQ75Aq+p6ExSBAc/uiGi0RnXuP9lLModjvauEkMDTVtfeeeN/NC+eQXI6zyorSHbvB0/AIhFc8A89KFGDjpPbGa+/w4qJ8q6OrrfLI+IAadt7E8DR1fcD+R+6ACcOLYszUr39GQB/uhGoF10sIhqZfcvw7cYGAGZSeI/l9RPN51n6AF5j4wIDAQAB
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC95SF8I5xJ7W2/I6uQOVB9MDiTKSptzCQDFTJCT4OIN3WTvbnN9g0qwVaDLlpxb40tcge/gsJMojvq8U1GmVNxe0dKS8uQYIpV36BsSEfT6jjpmlr2mLLb8A6VTE/MTGO+KN+PD8lsVOstUePIEn8fp53UIC0ptw0iO2lDvkCr6noTFIEBz+6IaLRGde4/2Usyh2O9q4SQwNNW19554380L55BcjrPKitIdu8HT8AiEVzwDz0oUYOOk9sZr7/Dionyro6ut8sj4gBp23sTwNHV9wP5H7oAJw4tizNSvf0ZAH+6EagXXSwiGpl9y/DtxgYAZlJ4j+X1E83nWfoAXmPjAgMBAAECggEARYgpy6fKaXNrtQpdnrCt3TkT7iarp4qRQSO4xHkTA4SzI8bbyyOmTJqAkAYgDds3yYUwexppBOB+qhdzIT+xQyNNxlGclyASZ0E8H4oT6u+fqUHgvtzI2Sm8XUSVD4yFFTMoMN0p9uXdOzn5+t9y9udMLkkd4GFriLZSZAC883WD70q+b2OGyZVNMeJxK2hp0DwUy+MK7JPNxxnnh5m/IHRQjDpOfOJBuU9xGIfZtzFExz8+gt95WmpytAa9YPuPNBtpIFDRmjSZAWEU8Rwu7OxO8l1EE+aRuNQrHmnDOG0Mt91ruYECHYtZc9cJum8vM5CEGCzvmZDs7j9j5cr3+QKBgQD9vsQv5sgG43a84rRjd/RyVwpix5F1vE4EN6dkUs+ZEclnnPRbJ1drMBvcDWyr/Hvrn054xych3WWoxQNV5P7XguNlK7cExVFQMmUxYy2D9FjvqosUdNmn0BWf/obp+nlSG9nji+J7+HfendsqeaNo8qIC+Zw/lnbhMOsLMilJ5wKBgQC/lR1WXQ4363smBzcJ9KaQoMtJA2rLnWeM8EZfMHD4MXJ11YCFuOfKtuQh27fvRxpQGbdvaF3aMDeVSvCGP8kBCApue7eliHTPhE2AK081woSNXDkGcJfrfJ8mNeBpaSMcXmk6nntXyy/YqGXOyn5ct747wLLE/fdJuZ6gvuvupQKBgHbv90e4tiO8dQiefw1sybDaqayZfM4iALOrXpQA2PwXwT8G6+baLvi4KSbhSAHprDBKkN6+AtK10xPjnOejGezslify8KuUzcN4i8Q1h70lSJa2atCg4PDu8WP4S0bbOAjLszscc4HGenFnrrZfI8BqkpQwahPINFrjshiiX4YbAoGAQBEBiov74T9iI0luYmnp+ZuL35LA9+5fXoZLQjHU1WrTuAv5ur4m5WdbyubLD71bU0YGTb89A2X0cHxrCrnx4eJqep/svfJv/aVktWPGTVgLM6qPd1PXuewm3IRP03BRSX9Y+T1eSfGswmsuAIU+1IqtlxXNsoqrU4A7R84Q3/ECgYAoFIlrdfQaXO39y5QKbHPSE9ZXV8EIyuc9E3n4aOc2KDhCrwtjyaeecf9/6947h523PWD8ZsweiBgYOdr3bKIoeDgc4rStgG6BN9CggOETGIDjV4R8QFdjSy/ehe2EUnvHBAxVpVR8H91fGuu7ckydP3X6U5F7BWlQRx73ETiCeg==