server:
  port: 60004
  servlet:
    context-path: /file

jasypt:
  encryptor:
    password: gszero

spring:
  application:
    name: blog-file
  redis:
    database: 0
    host: ${devServiceIp}
    port: 6379
    password: ENC(o8ZdpLA+3lVokD4Xd5801OYjaJCXdtKIUqPbz8+fU8s=)
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${devServiceIp}:3306/blog_file?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: ENC(CHAMoyE8XiIijQ7z2dhetMNMdeNXZhohLXw8mQ6KniCHgGtzfGHCyg==)
  servlet:
    multipart:
      max-file-size: 110MB # 设置单个文件大小
      max-request-size: 110MB # 设置单次请求文件的总大小

rocketmq:
  name-server: ${devServiceIp}:9876 # 访问地址
  producer:
    group: blog # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
  consumer:
    groupName: blog
    namesrvAddr: ${devServiceIp}:9876 # mq的nameserver地址
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: BLOG_USER_DATA~*;BLOG_SYSTEM_DATA~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1

mybatis:
  mapper-locations: classpath:/mapper/*.xml

#security:
#  oauth2:
#    resource:
#      id: blog-file
#      user-info-uri: http://${devServiceIp}:9200/auth/user-me
#      prefer-token-info: false
#
#file:
#  system: win
#  basePath: D:/files
#  baseUri: /files
#  serviceIp: http://${devServiceIp}
#
#netty:
#  host: 127.0.0.1
#  port: 9092