logLevel: info

rtsp: true
rtspAddress: :8554

# 关闭不需要服务
hls: false
playback: false
webrtc: false

# 默认配置模板
pathDefaults:
  source: publisher
  # 默认不开启录像
  record: false
  # 统一录像保存路径（你要求的目录）
  recordPath: /opt/docker/mediamtx/recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 1s
  recordMaxPartSize: 50M
  recordSegmentDuration: 600s
  # 保留时间
  recordDeleteAfter: 3d
  overridePublisher: true

paths:
  cam1:
    record: true   # 只需要启用录像，其余继承默认值