[mnt]
comment = All Mounted Disks
path = /mnt
browseable = yes
read only = no
valid users = nas
force user = nas
create mask = 0664
directory mask = 0775

# 性能参数（视频关键）
aio read size = 1
aio write size = 1
socket options = TCP_NODELAY SO_RCVBUF=262144 SO_SNDBUF=262144