worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;
        server_name _;

        # ==================================================
        # 工具访问
        #
        # /tool/excel
        #        ↓
        # /usr/share/nginx/html/excel/dist/index.html
        #
        # /tool/excel/assets/xxx.js
        #        ↓
        # /usr/share/nginx/html/excel/dist/assets/xxx.js
        #
        # /tool/其它项目
        #        ↓
        # /usr/share/nginx/html/其它项目/dist/
        # ==================================================

        location ~ ^/tool/([^/]+)(/.*)?$ {
            set $tool_name $1;
            set $tool_path $2;

            if ($tool_path = "") {
                rewrite ^ /$tool_name/dist/index.html break;
            }

            if ($tool_path != "") {
                rewrite ^/tool/[^/]+/(.*)$ /$tool_name/dist/$1 break;
            }

            root /usr/share/nginx/html;
        }
    }
}