worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    # 日志
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    server {
        listen 80;
        server_name _;

        # =========================
        # Excel 工具
        # =========================
        location /tool/excel/ {
            alias /usr/share/nginx/html/excel/dist/;

            # Vue / React SPA 路由支持
            try_files $uri $uri/ /tool/excel/index.html;
        }

        # =========================
        # 根路径
        # =========================
        location = / {
            return 302 /tool/excel/;
        }
    }
}