worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;
        server_name _;

        # Excel 工具
        location ^~ /tool/excel/ {
            rewrite ^/tool/excel/(.*)$ /excel/dist/$1 break;

            root /usr/share/nginx/html;

            try_files $uri $uri/ /excel/dist/index.html;
        }
    }
}