server:
  port: 8085
spring:
  application:
    name: res-server
  security:
    oauth2:
      resourceserver:
        jwt:
          #访问授权服务器 在OIDC中是一个非常重要的标识符，有助于标识身份提供者和验证ID Token
          issuer-uri: http://localhost:8084