spring:
  application:
    name: auth-server
  security:
    user:
      name: admin
      password: 123456
    oauth2:
      authorizationserver:
        client:
          auth-client:
            registration:
              client-id: auth-client
              client-name: 认证客户端
              client-secret: "{noop}123456"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:6200/login/oauth2/code/auth-client
              scopes:
                - openid

server:
  port: 6100
