devServiceIp: 49.232.129.253
serviceIp: 49.232.129.253

server:
  port: 10200
  servlet:
    context-path: /file
  ssl:
    # enabled: true  #开启ssl验证
    enabled: false  #开启ssl验证
    key-store: classpath:keystore.p12 #证书文件位置
    key-store-password: gszero  #上面的密钥口令
    key-store-type: PKCS12   #storetype 上面的类型
    key-alias: tomcat    #tomcat上面的alias  别名

spring:
  application:
    name: blog-file
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.0.7:8848
  redis:
    database: 0
    host: 172.18.0.6
    port: 6379
    password: redis-960
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.3:3306/blog_file?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: MySql@Admin123*.
  servlet:
    multipart:
      max-file-size: 110MB # 设置单个文件大小
      max-request-size: 110MB # 设置单次请求文件的总大小

rocketmq:
  name-server: 172.18.0.8:9876 # 访问地址
  producer:
    group: blog # 必须指定group
    send-message-timeout: 5000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
  consumer:
    groupName: blog
    namesrvAddr: 172.18.0.8:9876 # mq的nameserver地址
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: BLOG_USER_DATA~*;BLOG_SYSTEM_DATA~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1

mybatis:
  mapper-locations: classpath:/mapper/*.xml

security:
  oauth2:
    resource:
      id: blog-file
      user-info-uri: http://172.18.0.10:9200/auth/user-me
      prefer-token-info: false

file:
  system: linux
  basePath: /opt/files
  baseUri: /files
  serviceIp: http://${serviceIp}

netty:
  port: 9092