spring:
  redis:
    host: localhost
    port: 6379
    password: redis-960

easy-es:
  enable: false #默认为true,若为 false 则认为不启用本框架
  address : 10.1.200.43:8030 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  username: elastic #若无 则可省略此行配置
  password: WG7WVmuNMtM4GwNYkyWH #若无 则可省略此行配置

rocketmq:
  name-server: localhost:9876 # 访问地址
  producer:
    group: blog2 # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
  consumer:
    groupName: test
    namesrvAddr: localhost:9876 # mq的nameserver地址
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: BLOG_USER_DATA~*;BLOG_SYSTEM_DATA~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1