server:
  port: 8084
spring:
  application:
    name: auth-server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://123.207.202.131:3306/blog_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: MySql@Admin123*.
  data:
    redis:
      host: 123.207.202.131
      port: 6379
      password: redis-960@*

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
