[global]
    workgroup = WORKGROUP
    server string = pi server (Samba, Ubuntu)
    security = user
    map to guest = never

[nas]
    path = /mnt
    browseable = yes
    writable = yes
    valid users = nas
    force user = nas
    force group = nas
    create mask = 0777
    directory mask = 0777